# Generated by Django 2.2.4 on 2019-10-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Season', models.CharField(blank=True, max_length=200)),
                ('No_in_series', models.CharField(blank=True, max_length=200)),
                ('Company', models.CharField(blank=True, max_length=200)),
                ('Deal', models.CharField(blank=True, max_length=200)),
                ('Industry', models.CharField(blank=True, max_length=200)),
                ('Entrepreneur_Gender', models.CharField(blank=True, max_length=200)),
                ('Amount', models.CharField(blank=True, max_length=200)),
                ('Equity', models.CharField(blank=True, max_length=200)),
                ('Valuation', models.CharField(blank=True, max_length=200)),
                ('Corcoran', models.CharField(blank=True, max_length=200)),
                ('Cuban', models.CharField(blank=True, max_length=200)),
                ('Greiner', models.CharField(blank=True, max_length=200)),
                ('Herjavec', models.CharField(blank=True, max_length=200)),
                ('John', models.CharField(blank=True, max_length=200)),
                ('Oleary', models.CharField(blank=True, max_length=200)),
                ('Harrington', models.CharField(blank=True, max_length=200)),
                ('Guest', models.CharField(blank=True, max_length=200)),
                ('Sharks', models.CharField(blank=True, max_length=200)),
                ('pershark', models.CharField(blank=True, max_length=200)),
                ('DetailsNotes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(blank=True, max_length=200)),
                ('Episode', models.CharField(blank=True, max_length=200)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('social001', models.CharField(blank=True, max_length=200)),
                ('social002', models.CharField(blank=True, max_length=200)),
                ('social003', models.CharField(blank=True, max_length=200)),
                ('social004', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('investors', models.CharField(blank=True, max_length=200)),
                ('kitna', models.CharField(blank=True, max_length=200)),
                ('companytitle', models.CharField(blank=True, max_length=200)),
                ('companylink', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
