# Generated by Django 2.2.4 on 2019-10-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191031_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
