# Generated by Django 2.2.4 on 2019-10-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191031_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='companytitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.dataa'),
        ),
    ]
