# Generated by Django 2.2.4 on 2019-10-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191031_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='companytitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
